[application]

[web.app]
title = "Pocket Binder"
base_path = "/pocket-binder/"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
